# Generated by Django 3.0.8 on 2020-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=250)),
                ('mob_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
