# Generated by Django 3.0.8 on 2020-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credicxo', '0002_auto_20201207_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_info',
            name='role',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
